version: '3.7'
networks:
  CLOUD_NETWORK:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 100.10.10.1/8
services:
  auth-server:
    image: gitlab.peykasa.ir:4567/jlibraries/cloud:${AUTH_TAG}
    ports:
      - "${AUTH_SERVER_PORT}:${AUTH_SERVER_PORT}"
    volumes:
      - ./permissions:/tmp
    command: >
      bash -c "chmod 777 /tmp/permission.sh && dos2unix /tmp/permission.sh &&
      /tmp/permission.sh &&
      ./env.sh &&  /etc/init.d/pa-auth-server run"
      volumes:
      - ./permissions:/tmp
    environment:
      server.port: "${AUTH_SERVER_PORT}"
      spring.application.name: "${AUTH_APP_NAME}"
      spring.cloud.config.discovery.service-id: "${CONFIG_APP_NAME}"
      eureka.client.service-url.defaultZone: "http://discovery-service:${DISCOVERY_SERVER_PORT}/eureka"
    networks:
      - CLOUD_NETWORK


