version: '3.7'
networks:
  CLOUD_NETWORK:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 100.10.10.1/8

services:
  gateway-service:
    image: gitlab.peykasa.ir:4567/jlibraries/cloud:${GATEWAY_TAG}
    logging:
      driver: "json-file"
      options:
        max-file: "100"
        max-size: "1000m"
    ports:
      - "${GATEWAY_SERVER_PORT}:${GATEWAY_SERVER_PORT}"
    environment:
      server.port: ${GATEWAY_SERVER_PORT}
      spring.application.name: "${GATEWAY_APP_NAME}"
      spring.cloud.config.discovery.service-id: "${CONFIG_APP_NAME}"
      eureka.client.service-url.defaultZone: "http://discovery-service:${DISCOVERY_SERVER_PORT}/eureka"
      spring.main.allow-bean-definition-overriding: "true"
    networks:
      - CLOUD_NETWORK
